name: RN Android

on: [workflow_dispatch]
jobs:
# This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node
        uses: actions/setup-node@v2.1.2
        with:
         node-version: '14.15.0'
      - name: Installing Packages
        run: npm install
      - name: Running the build
        run: cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Collecting built files
        if: success() 
        uses: actions/upload-artifact@v2
        with:
        # Name of the command/step.
         name: release-apks
        # Path to the release apks.
         path: android/app/build/outputs/**/*.apk
